### PR TITLE
Read local IP address by method, not from cfg

### LINKED ISSUE #4: Reading local IP from config property breaks CF login when resurrected
The cf-registrar gets the local IP used to register at the router from its config. The IP is determined when the [configuration template](https://github.com/cloudfoundry/cf-release/blob/master/jobs/uaa/templates/cf-registrar.config.yml.erb#L14) is rendered by erb. 

This is a problem when the UAA gets resurrected by the BOSH Healthmonitor. Rendered configuration templates are cached in the BOSH director's blobstore. These template are used when resurrecting the VM, although it might get a different IP address. The UAA will then register with a wrong IP at the router and you cannot log into CF anymore.

All other CF components should not be affected as they don't use the cf-registrar.

As a solution, the cf-registrar could make sure to get the actual IP when started and not from a config property.

### PR DESCRIPTION
**Pull request by voelzmo**
resolves #4

### CODE REVIEW

**Comment by dieucao** [comment]
@chipchilders Is dreddbot not updated yet?  I see that @voelzmo has his membership of sap-cloudfoundry set to public.

**Comment by chipchilders** [comment]
There was an issue with deploying dreddbot changes that is now resolved. (I hope)

**Comment by voelzmo** [comment]
@dieucao @chipchilders seems like @cfdreddbot now recognizes that we have signed the CLA, see this PR for example: https://github.com/cloudfoundry/bosh-init/pull/29

**Comment by dieucao** [comment]
@voelzmo Cool.  We hope to get to reviewing these by the end of the week, but it might go into later next week due to summit.

**Comment by jpalermo** [comment]
The BOSH team thinks this is better fixed on their end.

https://www.pivotaltracker.com/story/show/94906096

**Pull request closed without merging**
